### PR TITLE
Setup vale tool.

### PR DESCRIPTION
**Pull request by proofit404**
Fixes https://github.com/dry-python/dependencies/issues/116.

### CODE REVIEW

**Comment by proofit404** [comment]
@thedrow Could you take a look at this PR?

Vale doesn't work for some reason even if I make spelling error intentionally.

**Comment by thedrow** [comment]
Works on my machine...
The outcome is:
```
✖ 20 errors, 114 warnings and 0 suggestions in 16 files.
```

**Comment by proofit404** [comment]
Thanks for the test!

**Comment by proofit404** [comment]
Superseded by #290

**Pull request closed without merging**
